version: 2.1

jobs:
  build:
    docker:
      - image: proteomics/cosmo:latest
    steps:
      - checkout
      - run: Rscript scripts/slimmed/preprocess.R $(pwd) scripts/COSMO/example_data/for_2b/Testing_1/test_pro.tsv scripts/COSMO/example_data/for_2b/Testing_1/test_rna.tsv scripts/COSMO/example_data/for_2b/Testing_1/test_cli.tsv